In [4]:
import numpy as np
a =  np.array([11,22,23,32])
print(a.dtype)

int32


In [5]:
b = np.array([11.0,12.0])
print(b.dtype)

float64


In [12]:
#you can also tell the data types
c = np.array([11,12],dtype = np.int64)
print(c.dtype)

int64


In [13]:
# you can also change the type like below similarly in float change may
d = np.array([11.1,12.9],dtype = np.int64)
print(d.dtype)
print(d)

int64
[11 12]


In [19]:
import numpy as np
x = np.array([[11,12,13],[21,22,23]],dtype = np.float64)
y = np.array([[9.9,8.4,7.3],[1.2,2.3,3.4]],dtype = np.int64)
print(x)
print()
print(y)

[[11. 12. 13.]
 [21. 22. 23.]]

[[9 8 7]
 [1 2 3]]


In [21]:
#add
print(x + y)
print()
print(np.add(x,y))

[[20. 20. 20.]
 [22. 24. 26.]]

[[20. 20. 20.]
 [22. 24. 26.]]


In [26]:
#subtract
print(x -y)
print()
print(np.subtract(x,y))

[[ 2.  4.  6.]
 [20. 20. 20.]]

[[ 2.  4.  6.]
 [20. 20. 20.]]


In [28]:
# multiply
print(x * y)
print()
print(np.multiply(x,y))

[[99. 96. 91.]
 [21. 44. 69.]]

[[99. 96. 91.]
 [21. 44. 69.]]


In [30]:
#divide
print(x / y)
print()
print(np.divide(x,y))

[[ 1.22222222  1.5         1.85714286]
 [21.         11.          7.66666667]]

[[ 1.22222222  1.5         1.85714286]
 [21.         11.          7.66666667]]


In [32]:
#square root
print(np.sqrt(x))
print()
print(np.sqrt(y))

[[3.31662479 3.46410162 3.60555128]
 [4.58257569 4.69041576 4.79583152]]

[[3.         2.82842712 2.64575131]
 [1.         1.41421356 1.73205081]]


In [33]:
#exponential (e**x)
print(np.exp(x))

[[5.98741417e+04 1.62754791e+05 4.42413392e+05]
 [1.31881573e+09 3.58491285e+09 9.74480345e+09]]
