# Index slicing

In [1]:
import numpy as np
array = np.array([[11 ,12 ,13],[21 ,22 ,23],[31 , 32 ,33]])
print(array)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


**syntax**

slice =  array[row_slice,column_slice] or array[1:3,0:2]

### print 2 rows and 2 column using slice indexing

In [4]:
print(array[:2,1:3])# it prints only sliced array
a_slice =  np.array(array[:2,1:3])#it will save the slices in a new array
print(a_slice)

[[12 13]
 [22 23]]
[[12 13]
 [22 23]]


In [6]:
row_rank1 = array[1, : ] # print row 2nd and and all the column
print(row_rank1,row_rank1.shape)

[21 22 23] (3,)


In [10]:
row_rank2 =  array[1:2,1:2 ]
print(row_rank2,row_rank2.shape)

[[22]] (1, 1)


## np.arange

In [14]:
row_indices = np.arange(7)
print(row_indices)# it will creat one dimensional array range of (n-1)

[0 1 2 3 4 5 6]


In [15]:
for row, column in zip(row_indices)

SyntaxError: invalid syntax (<ipython-input-15-ebb8e5a835c7>, line 1)

# ndarray boolean indexing

In [16]:
import numpy as np
an_array = np.array([[11,12],[21,22],[31,32]])
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [24]:
#filter keyword used to check the condition
filter =  (an_array > 15)
filter

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [25]:
# it will print only True values means which is greater than 15 according to above
print(an_array[filter])

[21 22 31 32]


In [29]:
an_array[(an_array > 20 ) & (an_array < 32)]

array([21, 22, 31])

In [30]:
an_array[(an_array % 2 == 0)]

array([12, 22, 32])

In [32]:
an_array[(an_array % 2 == 0)] += 100
print(an_array)

[[ 11 212]
 [ 21 222]
 [ 31 232]]
