<html>
    <head>
    </head>
    <body>
        <h1> Broadcasting
    </body>
</html>        


In [1]:
#creating a simple 4x3 array of zeros
import numpy as np
start = np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [2]:
add_rows = np.array([1, 0 ,2])
print(add_rows)

[1 0 2]


In [3]:
# now adding both matrix using beoadcasting there is a difference between rows and column
addition = start + add_rows
print(addition)#now [1,0,2] is added to each row of start

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [4]:
#noe creating 4x1 array using transpose method to add columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T # dot T used to transpose the matrix
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [5]:
# add each column to start using broadcasting
y = start + add_cols
print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [6]:
# now add in both dimensions
add_scalar = np.array([1])
print(start+add_scalar)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
