# Creat Rank array

In [1]:
import numpy as np
a = np.array([1,2,3]) # creat rank 1 array
print(type(a))

<class 'numpy.ndarray'>


In [2]:
print(a.shape) # test the shape of the array or order

(3,)


In [3]:
print(a[0],a[1])

1 2


## nd array is mutable so we can change the elements


In [4]:
a[1] = 64
print(a)

[ 1 64  3]


# Creat Rank 2 nd array


In [9]:
import numpy as np
b = np.array([[11,12,13],[61,51,81]])
print(b)

[[11 12 13]
 [61 51 81]]


In [10]:
print(type(b))

<class 'numpy.ndarray'>


In [11]:
print(b.shape) # it has 2 rows and 3 columns

(2, 3)


In [12]:
print(b[0][1]) # it print the **o th ** row nd 1 column

12


In [14]:
print(b[1][1]) # second row and second column

51


In [16]:
print(b[1][2])

81


## to creat 2,2 array of all zeroes

In [18]:
import numpy as np
c = np.zeros((2,2)) # arrray of zero element creating [2][2] 
print(c)

[[0. 0.]
 [0. 0.]]


## creating ones


In [19]:
import numpy as np
d = np.ones((3,3)) 
print(d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## creating arrays filled with 9.0

In [20]:
import numpy as np
e = np.full((2,2),9.0)
print(e)

[[9. 9.]
 [9. 9.]]


## creating identity matrix (diagonal is 1 other 0)

In [22]:
import numpy as np
f = np.eye(3,3) # **contains single paranthesis **
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
print(f.shape)

(3, 3)


In [24]:
print(e.shape)

(2, 2)
