# Statistical method ,Sorting and  Set operations

## Statistical method

### Random

In [9]:
# set up a random 2x4 matix
import numpy as np
arr =  10* np.random.randn(2,4) 
print(arr)

[[-0.02882382  7.94811345  3.40075667 -1.72064973]
 [-8.8214561   2.55898907  9.10711923  4.44552122]]


### MEan

In [10]:
#compute the mean of all elemnts
print(arr.mean())

2.111196249782


In [11]:
# compute the mean by row
print(arr.mean(axis = 1))

[2.39984914 1.82254336]


In [12]:
# compute the mean by column
print(arr.mean(axis = 0))

[-4.42513996  5.25355126  6.25393795  1.36243575]


In [13]:
# sum of all elments
print(arr.sum())

16.889569998256


In [14]:
# compute the median by row
print(np.median(arr, axis = 1))

[1.68596642 3.50225515]


## Sorting

In [16]:
# Creat a unsorted matrix 1x10
unsorted =  np.random.randn(10)
print(unsorted)

[ 1.06695995  0.06217221  0.02545481  1.56716272 -0.92683385 -1.7672885
  0.37905581 -0.07265041  1.18697741 -0.95904091]


In [20]:
#creat a copy of sort matrix
sorted =  np.array(unsorted)# it will creat a sorted array
sorted.sort() # it will print sorted array
print(sorted)
print()
print(unsorted)

[-1.7672885  -0.95904091 -0.92683385 -0.07265041  0.02545481  0.06217221
  0.37905581  1.06695995  1.18697741  1.56716272]

[ 1.06695995  0.06217221  0.02545481  1.56716272 -0.92683385 -1.7672885
  0.37905581 -0.07265041  1.18697741 -0.95904091]


In [21]:
# inplace sorting
unsorted.sort()
print(unsorted)

[-1.7672885  -0.95904091 -0.92683385 -0.07265041  0.02545481  0.06217221
  0.37905581  1.06695995  1.18697741  1.56716272]


## Finding unique elements

In [24]:
import numpy as np
array = np.array([1,1,2,3,4,4,6,2,3,4])
print(np.unique(array))

[1 2 3 4 6]


## set oprtaion with np.array data type


In [25]:
s1 =  np.array(["lion","cat",'wolf',"dog"])
s2 = np.array(["bear","tiger","dog","lion"])
print(s1,s2)

['lion' 'cat' 'wolf' 'dog'] ['bear' 'tiger' 'dog' 'lion']


In [26]:
# to find the common elemnts
print(np.intersect1d(s1,s2))

['dog' 'lion']


In [27]:
# find the union
print(np.union1d(s1,s2))

['bear' 'cat' 'dog' 'lion' 'tiger' 'wolf']


In [30]:
# find the difference
print(np.setdiff1d(s1,s2))
print(np.setdiff1d(s2,s1))

['cat' 'wolf']
['bear' 'tiger']


In [31]:
#which elemnt of s1 in s2
print(np.in1d(s1,s2))

[ True False False  True]


## 